# Generated by Django 3.0 on 2020-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120)),
                ('course_provider_name', models.CharField(max_length=120)),
                ('image_representing_course', models.ImageField(upload_to='')),
                ('iconimage_course_provider', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
