# Generated by Django 3.0 on 2021-01-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='iconimage_course_provider',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='image_representing_course',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
